### ??###stdout,
log4j.rootLogger=D22222,E,stdout
### ???????? ###
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[%-5p] %d{---yyyy/MM/dd HH:mm:ss,SSS---}method:%l%n%m%n
### ?? DEBUG ???????? = D://myJavaLogs/debug/log.log ###
log4j.appender.D22222=org.apache.log4j.DailyRollingFileAppender
log4j.appender.D22222.File=/home/ljj/Log/Debug.log
log4j.appender.D22222.Append=true
log4j.appender.D22222.Threshold=DEBUG 
log4j.appender.D22222.layout=org.apache.log4j.PatternLayout
log4j.appender.D22222.layout.ConversionPattern=%-d{yyyy-MM-dd HH:mm:ss} [ %t:%r ] - [ %p ] %m%n
### ?? ERROR ????????=D://myJavaLogs/error/error.log  ###
log4j.appender.E=org.apache.log4j.DailyRollingFileAppender
log4j.appender.E.File=/home/ljj/Log/Error.log
log4j.appender.E.Append=true
log4j.appender.E.Threshold=ERROR 
log4j.appender.E.layout=org.apache.log4j.PatternLayout
log4j.appender.E.layout.ConversionPattern=%-d{yyyy-MM-dd HH:mm:ss} [ %t:%r ] - [ %p ]
#??sql????
log4j.logger.java.sql.ResultSet=INFO
log4j.logger.org.apache=INFO
log4j.logger.java.sql.Connection=DEBUG
log4j.logger.java.sql.Statement=DEBUG
log4j.logger.java.sql.PreparedStatement=DEBUG
